% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Tugas Individu Minggu 7},
  pdfauthor={Shabrina Shafwah Al-Rahmah G1401221083},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Tugas Individu Minggu 7}
\author{Shabrina Shafwah Al-Rahmah G1401221083}
\date{2024-03-05}

\begin{document}
\maketitle

\hypertarget{data}{%
\section{Data}\label{data}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{14}\NormalTok{, }\DecValTok{19}\NormalTok{, }\DecValTok{26}\NormalTok{, }\DecValTok{31}\NormalTok{, }\DecValTok{34}\NormalTok{, }\DecValTok{38}\NormalTok{, }\DecValTok{45}\NormalTok{, }\DecValTok{52}\NormalTok{, }\DecValTok{53}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{65}\NormalTok{)}
\NormalTok{Y }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{54}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{45}\NormalTok{, }\DecValTok{37}\NormalTok{, }\DecValTok{35}\NormalTok{, }\DecValTok{25}\NormalTok{, }\DecValTok{20}\NormalTok{, }\DecValTok{16}\NormalTok{, }\DecValTok{18}\NormalTok{, }\DecValTok{13}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{11}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{6}\NormalTok{)}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(X,Y)}
\FunctionTok{library}\NormalTok{(DT)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'DT' was built under R version 4.3.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{datatable}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\includegraphics{tugas-individu_files/figure-latex/unnamed-chunk-1-1.pdf}

\hypertarget{eksplorasi-data}{%
\section{Eksplorasi Data}\label{eksplorasi-data}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ X, }\AttributeTok{data =}\NormalTok{ data)}

\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.3.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ X, }\AttributeTok{y =}\NormalTok{ Y)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Scatterplot"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\includegraphics{tugas-individu_files/figure-latex/unnamed-chunk-2-1.pdf}

Berdasarkan \emph{scatter plot} di atas, dapat dilihat bahwa peubah X
dan peubah Y membentuk suatu pola linier dari kiri atas ke kanan bawah.
Hubungan tersebut membentuk pola linier negatif.

\hypertarget{pemeriksaan-asumsi}{%
\section{Pemeriksaan Asumsi}\label{pemeriksaan-asumsi}}

\hypertarget{nilai-harapan-galat-sama-dengan-nol-eepsilon_i0}{%
\subsection{\texorpdfstring{Nilai harapan galat sama dengan nol
(\(E[\epsilon_i]=0\))}{Nilai harapan galat sama dengan nol (E{[}\textbackslash epsilon\_i{]}=0)}}\label{nilai-harapan-galat-sama-dengan-nol-eepsilon_i0}}

Plot sisaan vs \(\hat{y}\)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(model, }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{tugas-individu_files/figure-latex/unnamed-chunk-3-1.pdf}

Berdasarkan plot di atas, sisaan berada di sekitar nol sehingga nilai
harapan sama dengan nol. Namun, sisaan membentuk pola kurva parabola
sehingga ada kemungkinan ragam tidak homogen dan berarti model tidak
pas. Perlu transformasi Y untuk membentuk model yang lebih baik.

Uji Formal
\[H_0: E[\epsilon] = 0 \text{(nilai harapan galat sama dengan nol)}\]
\[H_1: E[\epsilon] \neq 0 \text{(nilai harapan galat tidak sama dengan nol)}\]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(coin)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'coin' was built under R version 4.3.2
\end{verbatim}

\begin{verbatim}
## Loading required package: survival
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(model}\SpecialCharTok{$}\NormalTok{residuals,}\AttributeTok{mu=}\DecValTok{0}\NormalTok{,}\AttributeTok{conf.level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  model$residuals
## t = -4.9493e-16, df = 14, p-value = 1
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -3.143811  3.143811
## sample estimates:
##     mean of x 
## -7.254614e-16
\end{verbatim}

Hasil bptest menunjukkan bahwa p-value \textgreater{} 0.05 sehingga tak
tolak \(H_0\). Hal ini mengindikasikan bahwa nilai harapan galat sama
dengan nol.

\hypertarget{ragam-galat-homogen-atau-homoskedastisitas-textvarepsilon-sigma2-i}{%
\subsection{\texorpdfstring{Ragam galat homogen atau homoskedastisitas
(\(\text{var}[\epsilon] = \sigma^2 I\))}{Ragam galat homogen atau homoskedastisitas (\textbackslash text\{var\}{[}\textbackslash epsilon{]} = \textbackslash sigma\^{}2 I)}}\label{ragam-galat-homogen-atau-homoskedastisitas-textvarepsilon-sigma2-i}}

Uji formal untuk mendeteksi homogenitas ragam sisaan dapat dilakukan
dengan uji Breusch-Pagan menggunakan fungsi bptest yang memiliki
hipotesis sebagai berikut. \[H_0: \text{var}[\epsilon] = \sigma^2 I\]
\[H_1: \text{var}[\epsilon] \neq \sigma^2 I\]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lmtest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'lmtest' was built under R version 4.3.2
\end{verbatim}

\begin{verbatim}
## Loading required package: zoo
\end{verbatim}

\begin{verbatim}
## Warning: package 'zoo' was built under R version 4.3.2
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'zoo'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{bptest}\NormalTok{(model, }\AttributeTok{data=}\NormalTok{data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  studentized Breusch-Pagan test
## 
## data:  model
## BP = 0.52819, df = 1, p-value = 0.4674
\end{verbatim}

Hasil bptest menunjukkan bahwa p-value \textgreater{} 0.05 sehingga tak
tolak \(H_0\). Hal ini mengindikasikan bahwa ragam sisaan homogen.

\hypertarget{galat-saling-bebas-eepsilon_i-epsilon_j-0}{%
\subsection{\texorpdfstring{Galat saling bebas
\(E[\epsilon_i, \epsilon_j] = 0\)}{Galat saling bebas E{[}\textbackslash epsilon\_i, \textbackslash epsilon\_j{]} = 0}}\label{galat-saling-bebas-eepsilon_i-epsilon_j-0}}

Plot Sisaan vs Urutan

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\AttributeTok{x =} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{dim}\NormalTok{(data)[}\DecValTok{1}\NormalTok{],}
     \AttributeTok{y =}\NormalTok{ model}\SpecialCharTok{$}\NormalTok{residuals,}
     \AttributeTok{type =} \StringTok{\textquotesingle{}b\textquotesingle{}}\NormalTok{, }
     \AttributeTok{ylab =} \StringTok{"Residuals"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"Observation"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{tugas-individu_files/figure-latex/unnamed-chunk-6-1.pdf}

Uji Formal \[H_0: E[\epsilon_i, \epsilon_j] = 0\]
\[H_1: E[\epsilon_i, \epsilon_j] \neq 0\]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(randtests)}
\FunctionTok{runs.test}\NormalTok{(model}\SpecialCharTok{$}\NormalTok{residuals)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Runs Test
## 
## data:  model$residuals
## statistic = -2.7817, runs = 3, n1 = 7, n2 = 7, n = 14, p-value =
## 0.005407
## alternative hypothesis: nonrandomness
\end{verbatim}

Hasil runs test menunjukkan bahwa p-value \textless{} 0.05 sehingga
tolak \(H_0\). Hal ini mengindikasikan bahwa ada autokorelasi atau
sisaan tidak saling bebas pada model.

\hypertarget{galat-menyebar-normal}{%
\subsection{Galat Menyebar Normal}\label{galat-menyebar-normal}}

Plot qq

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(model,}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{tugas-individu_files/figure-latex/unnamed-chunk-8-1.pdf}

Berdasarkan qq-plot tersebut, sisaan cenderung mendekati garis diagonal
yang mewakili distribusi normal sehingga galat menyebar normal.

Uji Formal \[H_0 = N\] \[H_1 \neq N\]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(model)
## W = 0.92457, p-value = 0.226
\end{verbatim}

Berdasarkan hasil uji \emph{Shapiro-Wilk} nilai p-value \textgreater{} 0
sehingga tak tolak \(H_0\). Hal ini menunjukkan bahwa galat menyebar
normal.

\hypertarget{dugaan-persamaan-regresi}{%
\section{Dugaan Persamaan Regresi}\label{dugaan-persamaan-regresi}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Y ~ X, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.1628 -4.7313 -0.9253  3.7386  9.0446 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 46.46041    2.76218   16.82 3.33e-10 ***
## X           -0.75251    0.07502  -10.03 1.74e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.891 on 13 degrees of freedom
## Multiple R-squared:  0.8856, Adjusted R-squared:  0.8768 
## F-statistic: 100.6 on 1 and 13 DF,  p-value: 1.736e-07
\end{verbatim}

Didapatkan dugaan persamaan regresi sebagai berikut. \[
\hat Y = 46.460 - 0.752X
\] Hasil pendugaan parameter regresi menunjukkan bahwa rataan dugaan
nilai y akan turun sebesar 0.752 jika \(X\) berubah satu satuan. Adapun
ketika x=0 (jika ada dalam selang pengamatan), maka dugaan rataan nilai
y akan bernilai sebesar 46.460.

\hypertarget{ukuran-kelayakan-model}{%
\section{Ukuran Kelayakan Model}\label{ukuran-kelayakan-model}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{summary\_model }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(model)}

\NormalTok{(r\_squared }\OtherTok{\textless{}{-}}\NormalTok{ summary\_model}\SpecialCharTok{$}\NormalTok{r.squared)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8855804
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(adj\_r\_squared }\OtherTok{\textless{}{-}}\NormalTok{ summary\_model}\SpecialCharTok{$}\NormalTok{adj.r.squared)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8767789
\end{verbatim}

\hypertarget{penanganan-masalah}{%
\section{Penanganan Masalah}\label{penanganan-masalah}}

Uji asumsi-asumsi yang telah dilakukan sebelumnya menunjukkan perlunya
transformasi agar terbentuk model yang lebih baik, salah satunya karena
terbentuknya pola parabola pada plot residual.

\hypertarget{transformasi-untuk-meluruskan-pola-parabola}{%
\subsection{Transformasi untuk Meluruskan: Pola
Parabola}\label{transformasi-untuk-meluruskan-pola-parabola}}

Transformasi ini dilakukan dengan Y diperkecil, yaitu
\(Y^* = \sqrt{Y}\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_transformed }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(X, }\FunctionTok{sqrt}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Y))}
\NormalTok{model2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(Y) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ X, }\AttributeTok{data=}\NormalTok{data\_transformed)}

\NormalTok{predicted\_values }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model, data)}
\NormalTok{predicted\_values2 }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model2, data\_transformed)}

\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(X,Y,}\AttributeTok{main=}\StringTok{"Data and Model"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"X"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Y"}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(X, predicted\_values, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(X, }\FunctionTok{sqrt}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Y), }\AttributeTok{main=}\StringTok{"Transformed Data and Model"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"X"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"sqrt(Y)"}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(X, predicted\_values2, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{tugas-individu_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{uji-asumsi-setelah-transformasi}{%
\section{Uji Asumsi Setelah
Transformasi}\label{uji-asumsi-setelah-transformasi}}

\hypertarget{nilai-harapan-galat-sama-dengan-nol}{%
\subsection{Nilai harapan galat sama dengan
nol}\label{nilai-harapan-galat-sama-dengan-nol}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(model2, }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{tugas-individu_files/figure-latex/unnamed-chunk-13-1.pdf}

Uji Formal
\[H_0: E[\epsilon] = 0 \text{(nilai harapan galat sama dengan nol)}\]
\[H_1: E[\epsilon] \neq 0 \text{(nilai harapan galat tidak sama dengan nol)}\]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(coin)}
\FunctionTok{t.test}\NormalTok{(model2}\SpecialCharTok{$}\NormalTok{residuals,}\AttributeTok{mu=}\DecValTok{0}\NormalTok{,}\AttributeTok{conf.level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  model2$residuals
## t = -1.0367e-16, df = 14, p-value = 1
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.229541  0.229541
## sample estimates:
##   mean of x 
## -1.1095e-17
\end{verbatim}

Hasil uji t-test menunjukkan bahwa p-value \textgreater{} 0.05 sehingga
tidak tolak H0. Hal ini mengindikasikan nilai harapan galat sama dengan
0.

\hypertarget{ragam-galat-homogen-atau-homoskedastisitas-textvarepsilon-sigma2-i-1}{%
\subsection{\texorpdfstring{Ragam galat homogen atau homoskedastisitas
(\(\text{var}[\epsilon] = \sigma^2 I\))}{Ragam galat homogen atau homoskedastisitas (\textbackslash text\{var\}{[}\textbackslash epsilon{]} = \textbackslash sigma\^{}2 I)}}\label{ragam-galat-homogen-atau-homoskedastisitas-textvarepsilon-sigma2-i-1}}

\[H_0: \text{var}[\epsilon] = \sigma^2 I\]
\[H_1: \text{var}[\epsilon] \neq \sigma^2 I\]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lmtest)}
\FunctionTok{bptest}\NormalTok{(model2, }\AttributeTok{data=}\NormalTok{data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  studentized Breusch-Pagan test
## 
## data:  model2
## BP = 0.93605, df = 1, p-value = 0.3333
\end{verbatim}

Hasil uji bptest menunjukkan bahwa p-value \textgreater{} 0.05 sehingga
tidak tolak H0. Hal ini mengindikasikan ragam galat homogen.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\AttributeTok{x =} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{dim}\NormalTok{(data)[}\DecValTok{1}\NormalTok{],}
     \AttributeTok{y =}\NormalTok{ model2}\SpecialCharTok{$}\NormalTok{residuals,}
     \AttributeTok{type =} \StringTok{\textquotesingle{}b\textquotesingle{}}\NormalTok{, }
     \AttributeTok{ylab =} \StringTok{"Residuals"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"Observation"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{tugas-individu_files/figure-latex/unnamed-chunk-16-1.pdf}

\hypertarget{galat-saling-bebas}{%
\subsection{Galat saling bebas}\label{galat-saling-bebas}}

Uji Formal \[H_0: E[\epsilon_i, \epsilon_j] = 0\]
\[H_1: E[\epsilon_i, \epsilon_j] \neq 0\]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(randtests)}
\FunctionTok{runs.test}\NormalTok{(model2}\SpecialCharTok{$}\NormalTok{residuals)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Runs Test
## 
## data:  model2$residuals
## statistic = -0.55635, runs = 7, n1 = 7, n2 = 7, n = 14, p-value = 0.578
## alternative hypothesis: nonrandomness
\end{verbatim}

Hasil runs test menunjukkan bahwa p-value \textgreater{} 0.05 sehingga
tidak tolak \(H_0\). Hal ini mengindikasikan bahwa tidak ada
autokorelasi atau sisaan saling bebas.

\hypertarget{galat-menyebar-normal-1}{%
\subsection{Galat Menyebar Normal}\label{galat-menyebar-normal-1}}

Uji Formal \[H_0 = N\] \[H_1 \neq N\]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(model2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(model2)
## W = 0.93128, p-value = 0.2852
\end{verbatim}

Berdasarkan uji \emph{shapiro-test} didapatkan bahwa p-value
\textgreater{} 0.05 sehingga tidak tolak \(H_0\). Artinya, galat
menyebar normal.

\hypertarget{ukuran-kelayakan-model-2}{%
\section{Ukuran Kelayakan Model 2}\label{ukuran-kelayakan-model-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{summary\_model2 }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(model2)}

\NormalTok{(r\_squared2 }\OtherTok{\textless{}{-}}\NormalTok{ summary\_model2}\SpecialCharTok{$}\NormalTok{r.squared)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9439477
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(adj\_r\_squared2 }\OtherTok{\textless{}{-}}\NormalTok{ summary\_model2}\SpecialCharTok{$}\NormalTok{adj.r.squared)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.939636
\end{verbatim}

\#Perbandingan Ukuran Kelayakan Model

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(table\_data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Model =} \FunctionTok{c}\NormalTok{(}\StringTok{"Model 1"}\NormalTok{, }\StringTok{"Model 2"}\NormalTok{),}
  \AttributeTok{R\_squared =} \FunctionTok{c}\NormalTok{(r\_squared, r\_squared2),}
  \AttributeTok{Adj\_R\_squared =} \FunctionTok{c}\NormalTok{(adj\_r\_squared, adj\_r\_squared2)}
\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Model R_squared Adj_R_squared
## 1 Model 1 0.8855804     0.8767789
## 2 Model 2 0.9439477     0.9396360
\end{verbatim}

Dapat terlihat bahwa baik \(R^2\) maupun \(R^2_\text{adj}\) memiliki
nilai yang lebih besar dan lebih mendekati nilai 1 pada model 2 hasil
transformasi daripada model pratransformasi sehingga dapat dikatakan
bahwa model 2 lebih layak dibandingkan model 1.

\hypertarget{pendugaan-parameter-regresi}{%
\section{Pendugaan Parameter
Regresi}\label{pendugaan-parameter-regresi}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = sqrt(Y) ~ X, data = data_transformed)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.53998 -0.38316 -0.01727  0.36045  0.70199 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  7.015455   0.201677   34.79 3.24e-14 ***
## X           -0.081045   0.005477  -14.80 1.63e-09 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.4301 on 13 degrees of freedom
## Multiple R-squared:  0.9439, Adjusted R-squared:  0.9396 
## F-statistic: 218.9 on 1 and 13 DF,  p-value: 1.634e-09
\end{verbatim}

Dugaan persamaan regresi hasil transformasi sebagai berikut. \[
\sqrt {Y^*} = 7.015 - 0.081X
\]

\hypertarget{tranformasi-balik}{%
\section{Tranformasi Balik}\label{tranformasi-balik}}

\[
\sqrt {Y^*} = 7.015 - 0.081X
\] \[
Y^* = (7.015 - 0.081X)^2
\] \[
Y^* = 49.210 - 1.136X + 0.00656X^2
\]

\end{document}
